### ISSUE TITLE
[Consulting Service] Hitachi MySQL 

### ISSUE THREAD

**Issue by tinova** [tinova/try-templates#1]
Consulting Service
===================

* **Company**: HDS
* **Documents link**: Link to gdrive

Procedure and emails described [here](https://docs.google.com/document/d/1M0h1oboWSAbWtu7NpkDzblDAQdj9MuWcyK0WKpSiAkA)

### Phase 1. Introduction and Access

* [ ] Send introduction and SSH key to customer

### Phase 2. Planning

* [] Verify SSH access to front-end
* [] Prepare the planning report
* [] Get approval from Lead Consultant for planning report
* [] Send planning report to customer

### Phase 3. Execution

* [] Connect to customer infrastructure and gather information
* [] Execute consulting tasks
* [] Send daily report with actions done to customer
* [] Prepare recommendations report
* [] Get approval from Lead Consultant for recommendations report
* [] Send report to the client
* [] Arrange presentation meeting
