### ISSUE TITLE
nu issue

### ISSUE THREAD

**Issue by tinova** [tinova/try-templates#4]
---
Engineering Service
===================

* **Company**:
* **Documents link**:

Procedure and emails described [here](https://docs.google.com/document/d/1J6NnbZ5J6qiDrq9ItSpFququpfSlir3d1yq-e7QUHVIes)

### Phase 1. Introduction and Access

* [ ] Send introduction and SSH key to customer

### Phase 2. Planning

* [ ] Verify SSH access to the front-ends & nodes if needed
* [ ] Verify root access if needed
* [ ] Prepare planning report
* [ ] Get approval from Lead Consultant for planning report
* [ ] Send planning report

### Phase 3. Execution

* [ ] Connect to customer infrastructure
* [ ] Execute engineering actions
* [ ] Send daily report with actions done to customer
* [ ] Prepare execution report
* [ ] Get approval from Lead Consultant for execution report
* [ ] Send report to the client
